### ISSUE TITLE
third last figure in Readme.md

### ISSUE THREAD

**Issue by fatmasevinck** [fatmasevinck/enetLTS#19]
Dear @marastadler 

"You add plots in Readme.md in the multinomial regression section that are not in the manuscript.
When plotting the coefficients in the first of these plots, the x-axis label is difficult to read. You could sort the features by importance and/or show only a subset of the coefficients."

Concerning your comment here, you are right. It is difficult to read x-axis label in that figure. But this is because of the number of variables. In multinomial example, we have quite a lot number of variables. That plot is the original plot which is produced directly by function plot.enetLTS(). If someone works with less number of variables, it will be easier to read the x-axis. 
In this paper, these figures provide some examples for the original plot functions.

**Comment by marastadler** [comment]
Dear @fatmasevinck,
Thanks for the reply to my comment.
Okay, but if this particular plot is not appropriate for your data, I recommend removing it from the tutorial.

**Comment by fatmasevinck** [comment]
@marastadler 
This plot is suitable for the data. These models are working with high dimensional data. That is why it is important to provide an example for high dimensional data. It is normal to have such an issue in the plot.

**Comment by fatmasevinck** [comment]
If this part is ok for you, dear @marastadler , I will close this issue.

**Comment by fabian-s** [comment]
I agree with @marastadler that this: 
![image](https://user-images.githubusercontent.com/998541/211283123-1e1d0028-1e80-45d7-aeff-ee6dd0a303d5.png)
is a  completly terrible plot: it's illegilble, the ordering on the x-axis is completely arbitrary, there's no justfication for using a line plot here since values are not connected, and it's completely unclear what, if any, information readers are supposed to read from it. That said, the README is not the JOSS paper, so this does not seem relevant for the ongoing review process.

**Comment by fatmasevinck** [comment]
This figure is deleted from README.md file considering the number of variables in this example. 
Thanks for your comment.
